### ISSUE TITLE
[chart/redis-ha][BUG] haproxy seems not to support dual stack

### ISSUE THREAD

**Issue by pburgisser** [DandyDeveloper/charts#198]
**Describe the bug**
Since the version 4.16.0, with the support of the dual ipv4 ipv6 stack, ha-proxy doesn't want start (in a argoCD deployment)
**To Reproduce**
1. Use Argo-CD Helm chart 4.8.0 and 4.7.0 with dependencies to redis-ha 4.16.0
2. The 3 haproxy are created with the default haproxy.cfg
3. See error form the haproxy logs:
```
Defaulted container "haproxy" out of: haproxy, config-init (init)
[NOTICE]   (1) : haproxy version is 2.4.9-f8dcd9f
[NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
[ALERT]    (1) : Starting proxy health_check_http_url: cannot create receiving socket (Address family not supported by protocol) [:::8888]
[ALERT]    (1) : Starting frontend ft_redis_master: cannot create receiving socket (Address family not supported by protocol) [:::6379]
[ALERT]    (1) : Starting frontend stats: cannot create receiving socket (Address family not supported by protocol) [:::9101]
[ALERT]    (1) : [haproxy.main()] Some protocols failed to start their listeners! Exiting.
```
4. Downgrade Argo-CD helm chart to 4.6.5 to depends on redis-ha 4.15.0
**Additional context**
Argo-CD values file (currated):
```
argo-cd:
  dex:
    envFrom:
      - secretRef:
          name: dex-ldap-credentials
  redis:
    enabled: false
  redis-ha:
    enabled: true
  controller:
    replicas: 2
    metrics:
      enabled: true
  server:
    replicas: 2
    metrics:
      enabled: true    
    clusterAdminAccess:
      enabled: false
    rbacConfig:
      policy.csv: |
        p, role:none, applications, *, */*, deny
        p, role:none, projects, *, *, deny
        p, role:none, clusters, *, *, deny
      policy.default: 'role:none'
    config:
      admin.enabled: 'false'
```
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.21.6+vmware.2

**Comment by DandyDeveloper** [comment]
@pburgisser I'll jump on this tomorrow morning.

**Comment by DandyDeveloper** [comment]
This should be resolved already in an adjustment made a while back for dual stack clusters.

**Comment by patrickshan** [comment]
actually we are still seeing this error with the 4.22.1 release

**Comment by DandyDeveloper** [comment]
@patrickshan Have you tried setting this to false? 

https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha/values.yaml#L201-L202
